
# Site Settings

title: Alexander Slotte  # Your Title 
subtitle: Microsoft MVP
email: alexander.slotte@gmail.com  # Your Email
description: >-  
  Alexander Slotte is a Microsoft MVP and Speaker
baseurl: "/devlopr-starter" # the subpath of your site, e.g. /blog
url: "https://alexanderslotte.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alexslotte
github_username:  aslotte

# Navigation 

urls:
    - text: About
      url: /
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact

# Author Details

author_logo: profile.png
author: Alexander Slotte
author_bio: Hi, my name is Alexander Slotte and I'm a Microsoft MVP and speaker. I love all things ML.NET and C#.  
author_email: "alexander.slotte@gmail.com"
author_location: United States
author_website_url: "https://alexanderslotte.com"

# social links
twitter_username: alexslotte
github_username:  aslotte
linkedin_username: alexander-slotte-2110a415

# Choose what to show ( true - display or false - don't display)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: false

author_work_experiences: 
            - company_name: Excella
              company_logo: excella.jpg
              company_url: https://excella.com
              designation: Lead Software Engineer
              description: Help companies reach their potential through technology
              visibility: true

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# pagination of posts
paginate: 4
per_page: 5
paginate_path: "/blog/page/:num/"

# Search ( add algolia credentials below )
algolia:
  application_id: D9WA1YKTRS # add your algolia app id
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: [] 
  nodes_to_index: 'article' 
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9b # add algolia search only api key 


# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Build settings

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build